config/routes.rb
Bcomp::Application.routes.draw do
  resources :pins

  devise_for :users
  get 'about' => 'pages#about'
  get 'projects' => 'pages#projects'
  get 'blog' => 'pages#blog'

  root 'pages#home'

 

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,#:recoverable, 
  		 :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  	
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<!--<div class="footer">
	<small class="muted credit">
		Created by <%= link_to "Sam Scott-Hake", "https://twitter.com/SS_Hake" %>
	</small>
</div> -->

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      
      <%= link_to "Buntingford Library Supporters Club", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
      		<li><%= link_to "Journal Articles", about_path %></li>
          <li><%= link_to "County Council Submission", projects_path %></li>
          <!--<li><%= link_to "Blog", blog_path %></li> -->
      	</ul> 
      	<!--<ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to "You are logged in", "#" %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
      	</ul> -->
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>BLSC</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
			<div class="container">
				<% flash.each do |name, msg| %>
					<% content_tag(:div, msg, class: "alert alert-#{name}") %>
				<% end %>
				<%= yield %>
				<%= render 'layouts/footer' %>
			</div>
	</body>
</html>

app/views/pages/about.html.erb
<div>
<h1>Inspiring Libraries; Buntingford’s response to the County Library Service</h1>

<h3>This article appeared in the January Buntingford Journal.</h3>

<p>The consultation period of the survey concerning the future of libraries in Hertfordshire expired on 7th December 2014.   The following Friday, 12th December, Teresa and Graham Bonner and I attended a meeting of the County Council’s Customer Service, Performance and Libraries Cabinet Panel to present our petition and submission.   There was one other delegation there, from Chorleywood, with a petition and we were both given three minutes to make a presentation.  At that time there had been 589 Library Service questionnaires returned from Buntingford, while our petition (both hard-copy and on-line) stood at 2216 signatures and there were 694 “likes” on Facebook.   The response from Buntingford residents and from those in the surrounding area has been truly amazing.   This, in no small measure, is due to the hard work and enthusiasm of the four girls from Freman College who took on the task of promoting the petition – Cassie Fraser-Shanley, Paige Allen and the Salamian sisters Roxi and Kiana.   We owe them a huge vote of thanks. </p> 

<p>Frances Button, Chair of the Cabinet Panel, indicated to us that notwithstanding the fact that the consultation period had closed she was prepared to accept such further signatures to our petition which might still be received.   A decision is not expected until February, so if you have not signed up yet you still have a chance to have your say.   The on-line petition will still be available via our website, Buntingford Library Supporters Club.com, where you can also read the full text of our submission (it’s too long to include in the Buntingford Journal).</p>

<p>In concluding my three minute presentation to the Cabinet Panel I mentioned that when the town held its late-night shopping event in November there were 534 people counted through the doors of the library.  I doubted that a “virtual librarian” could cope with this.   What I did not mention was that mulled wine and mince pies offered by the Buntingford Civic Society, who have supported the campaign so well, were undoubtedly an attraction.   But what it does indicate is that the library premises are capable of being used to far greater effect for the benefit of the whole community.   So the fight is not over yet.</p>

<p>One other piece of information was disclosed at the Cabinet Panel meeting.   We were allowed to listen to the agenda item relating to library performances and we were delighted to learn that Buntingford library outperforms most of the other Hertfordshire libraries.   Generally only those with new buildings or where there were special circumstances, such as an experimental late night opening, posted better figures for book issues and visitor numbers.   This reflects how good are our four library assistants, Chris, Jennie, Julie and Patricia, although they only work part-time.   Hopefully this will be recognised by the County Library Service.   It seems inconceivable they would want to replace them with volunteers.</p>

<p>The campaign has demonstrated in no uncertain terms the care people in Buntingford have for their library.   This has been clearly noted at County Hall.   At our last public meeting on 3rd December there were two county councillors present as well as the Deputy Director of the Library Service, Taryn Pearson and East Herts councillor, Jeff Jones.   Frances Button had an earlier meeting that afternoon in Harrow, but she specially made the journey to attend our meeting in the full knowledge that she was going to be late.   I think the message is getting home that there are other factors than bald statistics on which to base the decision concerning the future of the library.   The statistics for Buntingford are good, but its geographical location and the emotional support of the local population are equally, if not more, important.   There was no pre-planning for our campaign: it simply evolved out of the conviction held widely in the town that the Library Service’s proposals were wrong.</p>

<p>So now we wait.   If County Hall accepts our arguments we then embark on a different course: to build on the support the campaign has generated and to develop the library as the true hub of the community and the surrounding area.  This will need money spending on the premises to make them properly fit for purpose and we may need to encourage County Hall to make the funds available.   By happy coincidence on 18 December the Government’s Department for Culture Media and Sport published the Independent Library Report for England which highlights the fact that libraries fulfil a vital role as the hub of communities and do not simply loan books.   The Buntingford Library has a copy.  If you have time read it: it is very good and confirms all that is good about our library.   If despite our best efforts the County Council does not rule in our favour the campaign will go on although it is difficult to see how they can ignore this report, as the Buntingford library already performs very successfully the role outlined in it.</p>

Brian Thompson          

</div>

<h1>Buntingford Library Under Threat</h1>

<h3> This article appeared in the November Buntingford Journal. </h3>

<div>
<p>Buntingford has had a library for many years.  For some time it was in the old Technical Institute in Baldock Road.   Then in 1979 it moved to its present home at 77 High Street, formerly occupied by the International store (which had moved further down the High Street to premises now trading as Sainsbury’s).</p>

<p>Last year the County Library Service launched a review of its strategy and came up with proposals which it entitled “Inspiring Libraries”. Basically it proposed to allocate the various libraries (there are 46 of them) to one of three categories: Tier 1 will comprise the libraries in the largest towns, Tier 2 libraries will be those in smaller towns, while Tier 3 libraries will cover smaller communities and villages.   A further proposal is to cut the mobile library service.   While great emphasis is made on improving the service by increased use of IT and volunteers the main thrust is cutting costs: they aim to save £2.5 million over three years.</p>

<p>Buntingford library has been placed in Tier 3 which will mean that the current staff will be sacked and it will be run by volunteers with access to a “virtual librarian”.   The library may also be downsized to alternative premises – where this could be is not identified.   All this is subject to a public consultation which runs until 7 December 2014.   Unfortunately the questionnaire is somewhat confusing and it is entirely possible, if you wish to respond, to convey completely the wrong message.</p>

<p>A well- attended meeting was held at the library on Thursday 2 October at which concerns were clearly expressed.   Councillor Teresa Bonner, who previously worked at the library, but when made redundant was not allowed to continue to run the very successful Story Time as a volunteer (seems they have now changed their minds bout volunteers), explained to the meeting the reaction of the Town Council.   Letters have been sent to our MP and County Councillor and Teresa herself has appeared on the front page of our version of the Mercury.</p>   

<p>Many deficiencies in the Library Service proposals of Buntingford were identified:</p>
<p>1. Buntingford is not a village.   It is a town with its own Town Council and Mayor, Chamber of Commerce and weekly Charter market which dates back to 1360.</p>
<p>2. The majority of the libraries are located in the built-up western part of the County.   By contrast East Herts is poorly served.   Buntingford is situated in the centre, some distance from other major libraries such as Bishop’s Stortford, Royston, Stevenage, Hertford and Ware.   As such it is the focus for around 28 surrounding villages all of which will be adversely affected by the cut in the mobile library service.</p>
<p>3. The proposals appear to predicated on current population figures.  With currently approved and planned housing developments Buntingford will increase by 50% (incidentally increasing to Council Tax income of Hertfordshire C. C. proportionally-and Buntingford already pays the highest rate in the County).   So the demand for the library’s services locally can also be expected to increase.   Moreover there will be a similar increase in the population of the larger villages.   Braughing already has two new housing estates and a further 60 houses are proposed: Puckeridge has a substantial new housing estate being built and another proposed.</p>
<p>4. The location of the Buntingford library, central in the High Street, is a very important factor, as evidenced by the response of Buntingford residents to the original questionnaire: 86% combine their visits with shopping compared with 82% for the survey as a whole.   Three hours free parking thanks to the Town Council is obviously a factor.  Shopkeepers have indicated that any downgrading or move of the library to different premises could have a serious prejudicial impact on the Town as a shopping centre.   In addition the library fulfils and important role in the social life of the Town which it must retain.   The weekly Story Time sessions introduces young children to the idea of books and visiting the library: at the other end of the age scale the monthly Local History group has been flourishing for over two years: and the library supports many local Book clubs.   </p>
<p>5. The proposed strategy says that the Library Service must increase its income.   Buntingford library can generate income if allowed to develop opportunities which have been denied in the past.   Visits by authors have been few and far between; instruction in the use of laptops, tablets etc which has been available elsewhere in the county has not been taken up although there has been the occasional instruction in PC use; hiring out the premise has not been very successful (it is believed that an unrealistic county charging rate has been responsible for this and it is encouraging that the latest document seems to have accepted that local hire rates should be applied).   Another reason for this is that the Buntingford premises have not been developed properly.   Behind the attractive area of the lending library, with its rows of books and computers, a large back office space is available.   The main problem is the steep access ramp.   Proposals to rectify this in the past have been largely ignored.   To replace the ramp with steps and a disabled lift (like the one in Pearce’s Farm shop or John Lewis WGC) would not be hugely expensive.   The meeting on 2 October identified several ideas for using this space such as an art gallery, music rooms, drama rooms, lectures, classes and societies.</p>

<p>The interest of local people in the future of our library was demonstrated in the response to the original 2013 consultation.   There were 383 responses from Buntingford, 2.5% of the total, while the average number of respondents from all 46 libraries was 336-the Buntingford response was almost 14% higher.    Buntingford folk were more likely to be exclusive users (54% against 32%).   This undoubtedly reflects the more isolated location of the town compared with the rest of the county and reinforces the argument for a more preferential treatment by the Library Service rather than a downgrading. </p>

<p>What is the way ahead?   A working group was established to prepare a considered paper which can be submitted to the County either a stand- alone document or attached to the formal questionnaire: a petition has been produced which is available to sign in the many shops in the town; the Mayor and Town Council are pursuing  the matter through their formal links with the County Council; the campaign will also feature on a website, buntingfordlibrarysupportersclub.co.uk and Facebook; and the Mercury will be kept up to date with its progress.   There will be another meeting at the library on Monday 3 November at 4.00pm when it is expected that the author of the latest consultation document will be in attendance and will be surely quizzed.  With the consultation period ending in December we understand that the final decision will not be taken much before February/March 2015.   So make sure we get the right one!   Support the campaign.</p>

Brian Thompson   

</div>      



    

  


app/views/pages/home.html.erb
<% if user_signed_in? %>
	<div>
		<h1>Hello</h1>
	</div>	
<% else %>

	<div class="hero-unit">
		<h2>Save Buntingford Library!</h2>
		<p class="lead">
			The consultation period has ended but you can still make a difference! <br> <br>

			You can still sign our petitions available in shops along the High Street.  <br> <br>

			Please visit and like our Facebook page to stay updated!

			<!--<br> <br> You can also sign our <br> <h3><a href="http://www.change.org/p/hertfordshire-county-council-save-buntingford-library">E-Petition!</a></h3>

			<% link_to "Save Buntingford Library", "http://www.change.org/p/hertfordshire-county-council-save-buntingford-library", class: "btn btn-success btn-large" %>-->
		</p>
		
	</div>
	<div>



	</div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>